### ISSUE TITLE
ci(e2e) #48 follow-up: triage the now-visible CI Suite failures (inventory @ 0e44880, post #45/#46/#47/#49/#50/#53/#54 wave)

### ISSUE THREAD

**Issue by 1StepMore** [1StepMore/e2e-test-suite#56]
Parent: #48 (the `2>&1 | tail -N` pipes hid these; the honest-gate fix is in PR fix/48-e2e-honest-pipefail). This is the triage umbrella — split into per-family issues as each gets a confirmed root cause.

**Reproduction (hermetic, no LLM keys):**
```bash
OMNI_TEST_FAKE_LLM=1 OMNI_TEST_FAKE_PANDOC=1 .venv_ol/bin/python -m pytest tests/ -m "not nightly" --tb=line -q -p no:cacheprovider
```
Measured at suite `0e44880` + OPP `a554f9c` + OL `1ee7744` + ORF `a63473c` (all fixes from the 2026-09-21 wave merged): **102 failed, 1350 passed, 19 skipped, 25 deselected, 8 xfailed, 8 xpassed, 18 errors**. Down from #48's 71+61 because #46/#47/#53/#94 fixes landed.

## Tier 1 — deterministic, env-independent (fix first)
| Family | n | Evidence |
|---|---|---|
| `tests/test_e2e_pipeline_full.py` | 18 errors | pipeline_chain setup/teardown errors (pptx/html × docx/epub/html × cli/mcp) — need full traceback |
| `ol_pool/router.py:418` | 5 | `AttributeError: 'ModelPool' object has no attribute '_breakers'` — `_breakers` IS set in `__init__` (router.py:353); partial-init or mock path leaks. Cascades into scene_07/LQA/exit-code failures |
| `tests/test_scene_07_multi_lang.py` | 12 | `OL failed [en-{ru,ja,fr} × {pdf,json,html,docx}]` — likely the `_breakers` cascade |
| `tests/test_ol_lqa_autoinvoke.py` | 7 | LQA auto-invoke family |
| `tests/test_format_matrix_verifier.py` | 4 | `TypeError: CellResult.__init__() missing 1 required positional argument: 'duration_s'` (verifier API drift, tests not updated) |
| `tests/test_mcp_smoke.py` | 6 | `OPP_RATE_LIMITED`/`RATE_LIMITED` on happy paths (token bucket not disabled for this step; only the MCP-verifier step sets `OMNI_RATE_LIMIT_RPM=0`); OL `translate_md_text` → `attempted relative import with no known parent package`; `KeyError: 'total'` ×2 |
| `tests/test_e2e_pipeline_failures.py` | 5 | `md_cli: expected rc != 0, got rc=0` (OL failure swallowed); `xliff_cli` surfaces quality-gate text instead of the XLIFF parse error |
| `tests/test_e2e_orf_mcp.py` / `test_e2e_opp_mcp.py` | 5 | `KeyError: 'format'/'failed'/'success_count'` — MCP response schema drift vs tests |
| `tests/test_e2e_image_md_path.py` | 4 | auto-detected `images.json` not found |
| `tests/test_corpus_fidelity_equivalence.py` | 5 | `assert 0 == 1`; `PackageNotFoundError: sample.docx` (pipeline produced nothing) |
| `tests/test_no_hardcoded_fake_llm.py` | 1 | 3 hardcoded `OMNI_TEST_FAKE_LLM=1` literals in Omni_Suite |
| `tests/test_no_broad_except.py` | 1 | 1 broad-except violation without logging/re-raise in Omni_Localizer |
| `tests/test_pipeline_default_output_survives.py`, `test_omni_suite_cli.py`, `test_e2e_path_*`, `test_e2e_images`, `test_e2e_04_fix`, `test_docs_versions_match_code`, `test_cross_format_e2e`, `test_agent_docs`, `validation/test_known_gap` (`'invalid' != 'known-gap'`), `validation/test_dispatch` | 13 | singles — triage individually |

## Tier 2 — pass in isolation, fail in the full run (inter-test pollution, NOT code bugs)
Verified: `tests/security/test_{ol,opp,orf}_mcp_path_traversal.py` (6), observability (`test_mcp_health`, `test_circuit_breaker`, `test_health`), `tests/mcp/test_ol_mcp_stdio.py`, `tests/error_scenarios/test_exit_code_matrix.py`, `tests/fidelity/test_fidelity_scorer.py`, `tests/distributed_tracing/test_distributed_tracing.py` — all PASS when run alone (spot-verified 5 security cases: `5 passed`). Root cause is shared state (token-bucket RPM, env leakage). Fix = isolate the rate limiter / env between groups.

## Tier 3 — local dev-venv skew only (do NOT file against code)
`tests/contract/test_cli_help.py::test_ol_help_contract` + `test_e2e_ol_cli.py::test_ol_help`: the shared `.venv_ol` has typer 0.26.2 while `uv.lock` pins 0.24.2 (renders `COMMAND` vs `[COMMAND] ``). CI (`uv sync --locked`) is authoritative.

## Module-repo items surfaced by the same gate (filed separately in their repos)
- OPP: `Omni_Pre_Processor/tests/test_opp_ol_orf_contracts_md.py` collection interrupt — `pytest.skip` outside a test without `allow_module_level=True` kills the WHOLE OPP group (1 error, 0 tests run). Verified: exit 2 in 43s.
- OL: `tests/test_ol_mcp_error_boundary.py::TestOPPErrorBoundary::test_opp_error_boundary_does_not_leak_exception_message` — `module_from_spec` without `sys.modules` registration; dataclass resolution fails on py3.13 (`AttributeError: 'NoneType' object has no attribute '__dict__'` at dataclasses.py:757).
- ORF: `tests/test_md2pdf_channel.py::TestMD2PDFConverter::test_convert_weasyprint_import_error` — `find_spec` patch ineffective once weasyprint is importable; converter falls back to pandoc and succeeds (`assert True is False`).

**Acceptance:** every Tier-1 family either fixed or split into its own issue with a confirmed root cause; Tier-2 pollution fixed by making the gate order-independent (rate limiter off / env scrubbed per group).

**Comment by 1StepMore** [comment]
## 本 umbrella 的两处结论需要修正（附实测证据）

### 1. Tier 3 的 “CI is authoritative / do NOT file against code” 不成立

Tier 3 把 `test_ol_help_contract` 归为本地 dev-venv 偏差（`.venv_ol` typer 0.26.2 vs lock 0.24.2），结论是"CI 权威、不要提代码 issue"。实测相反 —— **CI 自己在 Structural gate 上红**：

- run **35558229683**（main `8212fc9b`）→ job `Structural (hermetic, no keys)` step 17 `Gate 4 — Contract + validation engine tests` → `test_cli_help.py::test_ol_help_contract` FAILED，`1 failed, 506 passed`
- `expected`（fixture）= `Usage: ol_cli.py [OPTIONS] [COMMAND] [ARGS]...`，`actual` = `... [OPTIONS] COMMAND [ARGS]...`
- 根因实测：该 job 的 venv 里 typer 是 **0.27.2**（日志 "Install 3 sub-repos as editable packages" 步骤输出 `+ typer==0.27.2`），而 `uv.lock` 钉 **0.24.2** —— `uv sync --locked` 之后又被 `uv pip install -e ./Omni_*` 无锁重解析抬版。契约 fixture 的 oracle 与实际运行环境不一致。

→ 已提 **#58**（e2e-test-suite）跟进，请把 Tier 3 这一行从"不要提"改为"已提 #58"。

### 2. “Module-repo items … filed separately in their repos” 与实际不符

OPP 的 `tests/test_opp_ol_orf_contracts_md.py` collection 中断当时在 OPP 仓**没有任何 issue**（open 数为 0）。现已补提 **Omni_Pre_Processor#64**（模块级 `pytest.skip` 缺 `allow_module_level=True` → collection 中断 → OPP 组 0 用例执行、其后 5 个 CI 步骤全部 skipped）。

### 附：本轮巡检另外发现的 main 红（不在本 umbrella 内）

- **Omni_Pre_Processor#63** — OPP `validate` job：`ModuleNotFoundError: No module named 'yaml'`（suite 根包未声明 PyYAML，而 `omni_mcp/validation/cli.py:56` 模块级 import yaml）；validate 系首次真跑即挂。
- **Omni_Re_Formatter#50** — ORF `validate` job：`uv --no-config lock --check` 在空的工作区根目录执行（PR #49 引入 `path: orf-src` 后该步骤缺 `working-directory`）→ exit 2。
- **#59**（本仓）— `lint (blocking)` 红：hook `omni-doc-inventory` 报 16 处死路径 token（`validation-runs/latest.txt` / `Omni_Localizer/config/local.yaml` / `.env`，均不存在或被 gitignore）。

**Comment by 1StepMore** [comment]
Closing the umbrella per its own acceptance: every Tier-1 family is now either fixed or split into its own issue, and the Tier-2 inter-test pollution is FIXED.

## Progression of the "Run suite-level e2e tests" step
- #56 baseline (0e44880): 102 failed, 18 errors
- post wave-2 (PR #62, b77faf6): 61 failed, 18 errors — OPP/OL/ORF module steps green
- post Tier-2 fix (PR #87, 164a8c9): 38 failed, 18 errors — all pollution families green (observability, circuit_breaker, mcp_health, tracing_health, ol_mcp_stdio, fidelity_scorer, 3x path_traversal = 22 failures gone)

## Tier-2 (order-independence) — FIXED
PR #87 (164a8c9): conftest baselines the three fail-CLOSED allowlists via setdefault, an autouse fixture snapshots/restores os.environ per test, and the MCP token-bucket state is dropped between tests (the limiter itself stays covered by its own unit tests) + a new in-process guard test (tests/test_mcp_state_isolation_guard.py). One intentional test-sync commit aligns stale assertions with current module contracts (21 OL MCP tools, ol-mcp server name, nested ping envelope, health port 8767, two mathematically-impossible fidelity assertions) — none weakened; the ORF no-allowlist test was TIGHTENED to a strict fail-CLOSED pytest.raises.

## Tier-1 — split into per-family issues
- #74 stale ol_mcp.tools.ModelPool seam (18 errors + 6 across 5 files)
- #75 MCP response-envelope drift (test_e2e_opp_mcp/test_e2e_orf_mcp)
- #76 OL Gate 6 SOURCE_SCRIPT_FRAGMENT under FAKE_LLM (xliff_cli chains)
- #77 pipeline_failures[md_cli] stale failure-injection rebind
- #78 OL images.json forwarding absent + malformed PNG fixture (4)
- #79 corpus_fidelity_equivalence (6, three causes)
- #80 format_matrix_verifier CellResult signature drift (4)
- #81 test_e2e_04_fix hardcoded /mnt/d repo root (2)
- #82 validation engine: fake-active invalid overrides known-gap
- #83 docs tagline exact-match vs appended changelog pointer
- #84 e2e_images PDF page_number needs optional docling extra
- #86 apply-xliff --force warns FORCE MODE then hard-fails
- #85 was filed and is already CLOSED — fixed by PR #87 itself (fixture frontmatter).

## Residual (explicitly NOT claimed fixed)
#88 — 5 combined-run-only OPP path-denied failures in test_e2e_opp_mcp (mock provably active, real validator ran) + 1 floating-images skeleton miss. Alone-green, pair-green, CI-only; root cause NOT yet confirmed — the issue carries a falsifiable next diagnostic instead of a guess.

Evidence runs: 35615147574 (pre), 35641745008 (post, artifact suite-tests.log). Per-family fixes land against the child issues.
